swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /families:
    get:
      operationId: families.read_all
      tags:
        - Families
      summary: Read the entire set of families, sorted by last name
      description: Read the entire set of families, sorted by last name
      responses:
        200:
          description: Successfully read families set operation
          schema:
            type: array
            items:
              properties:
                family_id:
                  type: integer
                  description: Id of the family
                family_name:
                  type: string
                  description: First name of the family
                timestamp:
                  type: string
                  description: Create/Update timestamp of the family
                materials:
                  type: array
                  items:
                    properties:
                      family_id:
                        type: integer
                        description: Id of family this material is associated with
                      material_id:
                        type: integer
                        description: Id of this material
                      content:
                        type: string
                        description: content of this material
                      timestamp:
                        type: string
                        description: Create/Update timestamp of this material

    post:
      operationId: families.create
      tags:
        - Families
      summary: Create a family
      description: Create a new family
      parameters:
        - name: family
          in: body
          description: Family to create
          required: True
          schema:
            type: object
            properties:
              family_name:
                type: string
                description: First name of family to create
      responses:
        201:
          description: Successfully created family
          schema:
            properties:
              family_id:
                type: integer
                description: Id of the family
              family_name:
                type: string
                description: First name of the family
              timestamp:
                type: string
                description: Creation/Update timestamp of the family record

  /families/{family_id}:
    get:
      operationId: families.read_one
      tags:
        - Families
      summary: Read one family
      description: Read one family
      parameters:
        - name: family_id
          in: path
          description: Id of the family to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read family from families data operation
          schema:
            type: object
            properties:
              family_id:
                type: string
                description: Id of the family
              family_name:
                type: string
                description: First name of the family
              timestamp:
                type: string
                description: Creation/Update timestamp of the family record
              materials:
                type: array
                items:
                  properties:
                    family_id:
                      type: integer
                      description: Id of family this material is associated with
                    material_id:
                      type: integer
                      description: Id of this material
                    material_name:
                      type: string
                      description: content of this material
                    timestamp:
                      type: string
                      description: Create/Update timestamp of this material

  /families/{family_id}/calculate:
    get:
      operationId: families.calculate
      tags:
        - Families
      summary: Read one family
      description: Read one family
      parameters:
        - name: family_id
          in: path
          description: Id of the family to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read family from families data operation
          schema:
            type: object
            properties:
              family_id:
                type: string
                description: Id of the family
              family_name:
                type: string
                description: First name of the family
              timestamp:
                type: string
                description: Creation/Update timestamp of the family record
              materials:
                type: array
                items:
                  properties:
                    family_id:
                      type: integer
                      description: Id of family this material is associated with
                    material_id:
                      type: integer
                      description: Id of this material
                    material_name:
                      type: string
                      description: content of this material
                    timestamp:
                      type: string
                      description: Create/Update timestamp of this material


    put:
      operationId: families.update
      tags:
        - Families
      summary: Update a family
      description: Update a family
      parameters:
        - name: family_id
          in: path
          description: Id the family to update
          type: integer
          required: True
        - name: family
          in: body
          schema:
            type: object
            properties:
              family_name:
                type: string
                description: First name of the family
      responses:
        200:
          description: Successfully updated family
          schema:
            properties:
              family_id:
                type: integer
                description: Id of the family in the database
              family_name:
                type: string
                description: First name of the family
              timestamp:
                type: string
                description: Creation/Update timestamp of the family record

    delete:
      operationId: families.delete
      tags:
        - Families
      summary: Delete a family from the families list
      description: Delete a family
      parameters:
        - name: family_id
          in: path
          type: integer
          description: Id of the family to delete
          required: true
      responses:
        200:
          description: Successfully deleted a family

  /materials:
    get:
      operationId: materials.read_all
      tags:
        - Materials
      summary: Read the entire set of materials for all families, sorted by timestamp
      description: Read the entire set of materials for all families, sorted by timestamp
      responses:
        200:
          description: Successfully read materials for all families operation
          schema:
            type: array
            items:
              properties:
                material_id:
                  type: integer
                  description: Id of the material
                material_name:
                  type: string
                  description: Content of the material
                timestamp:
                  type: string
                  description: Create/Update timestamp of the material
                family:
                  type: object
                  properties:
                    family_id:
                      type: integer
                      description: Id of associated family
                    family_name:
                      type: string
                      description: Frist name of associated family
                    timestamp:
                      type: string
                      description: Create/Update timestamp of associated family


  /families/{family_id}/materials:
    post:
      operationId: materials.create
      tags:
        - Materials
      summary: Create a material associated with a family
      description: Create a material associated with a family
      parameters:
        - name: family_id
          in: path
          description: Id of family associated with material
          type: integer
          required: True
        - name: material
          in: body
          description: Text content of the material to create
          required: True
          schema:
            type: object
            properties:
              content:
                type: string
                description: Text of the material to create
      responses:
        201:
          description: Successfully created a material
          schema:
            properties:
              family_id:
                type: integer
                description: Id of the family associated with the material
              material_id:
                type: integer
                description: Id of the created material
              content:
                type: string
                description: Text content of the material
              timestamp:
                type: string
                description: Creation/Update timestamp of the family record

  /families/{family_id}/materials/{material_id}:
    get:
      operationId: materials.read_one
      tags:
        - Materials
      summary: Read a particular material associated with a family
      description: Read a particular material associated with a family
      parameters:
        - name: family_id
          in: path
          description: Id of family associated with material
          type: integer
          required: True
        - name: material_id
          in: path
          description: Id of material
          type: integer
          required: True
      responses:
        200:
          description: Successfully read material for a family
          schema:
            type: object
            properties:
              material_id:
                type: integer
                description: Id of the material
              family_id:
                type: integer
                description: Id of the family material associated with
              material_name:
                type: string
                description: Text content of the material
              timestamp:
                type: string
                description: Creation/Update timestamp of the material record

    put:
      operationId: materials.update
      tags:
        - Materials
      summary: Update a material associated with a family
      description: Update a material associated with a family
      parameters:
        - name: family_id
          in: path
          description: Id the family to update
          type: integer
          required: True
        - name: material_id
          in: path
          description: Id of the material associated with a family
          type: integer
          required: True
        - name: material
          in: body
          schema:
            type: object
            properties:
              material_name:
                type: string
                description: Text content of the material to updated
      responses:
        200:
          description: Successfully updated material
          schema:
            properties:
              material_id:
                type: string
                description: Id of the material associated with a family
              family_id:
                type: integer
                description: Id of the family in the database
              material_name:
                type: string
                description: Text content of the updated material
              timestamp:
                type: string
                description: Creation/Update timestamp of the material record

    delete:
      operationId: materials.delete
      tags:
        - Materials
      summary: Delete a material associated with a family
      description: Delete a material associated with a family
      parameters:
        - name: family_id
          in: path
          description: Id of family associated with material
          type: integer
          required: True
        - name: material_id
          in: path
          description: Id of material
          type: integer
          required: True
      responses:
        200:
          description: Successfully deleted a material
